from __future__ import annotations

from typing import Any

HEALTH_CONDITIONS = [
    "Diabetes",
    "High BP",
    "Low BP",
    "Thyroid",
    "PCOS",
    "Obesity",
    "Kidney Disease",
    "Fatty Liver",
    "High Cholesterol",
    "Heart Disease",
    "Acidity / GERD",
    "Gastritis",
    "IBS",
    "Pregnancy",
]

SENSITIVITY_OPTIONS = [
    "Mango Allergy",
    "Citrus Allergy",
    "Caffeine Sensitivity",
    "Artificial Sweetener Sensitivity",
    "Preservative Sensitivity",
]

CONDITION_DISPLAY = {item.lower(): item for item in HEALTH_CONDITIONS}
SENSITIVITY_DISPLAY = {item.lower(): item for item in SENSITIVITY_OPTIONS}

BEVERAGE_LIBRARY: dict[str, dict[str, Any]] = {
    "7_up": {
        "display_name": "7 Up",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 105, "sugar_g": 26, "sodium_mg": 40, "caffeine_mg": 0, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Lemon-lime flavour", "Citric acid", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "citrus", "preservative"],
        "good_for": ["Occasional intake by adults without diabetes or acidity issues"],
        "avoid_for": ["Users with diabetes", "Users with acidity or gastritis", "Children needing low-sugar drinks"],
    },
    "Coca_Cola": {
        "display_name": "Coca-Cola",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 110, "sugar_g": 27, "sodium_mg": 18, "caffeine_mg": 24, "acidity": 9},
        "ingredients": ["Carbonated water", "Sugar", "Caramel colour", "Phosphoric acid", "Natural flavours", "Caffeine"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "preservative"],
        "good_for": ["Healthy adults taking it occasionally in small portions"],
        "avoid_for": ["Users with diabetes", "Users with GERD or acidity", "Users with caffeine sensitivity"],
    },
    "Fanta": {
        "display_name": "Fanta Orange",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 120, "sugar_g": 30, "sodium_mg": 24, "caffeine_mg": 0, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Orange flavour", "Citric acid", "Food colours", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "citrus", "preservative"],
        "good_for": ["Occasional use by users with no blood-sugar or gastric concerns"],
        "avoid_for": ["Users with citrus allergy", "Users with diabetes", "Users with acidity"],
    },
    "Frooti": {
        "display_name": "Frooti",
        "category": "fruit_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 130, "sugar_g": 31, "sodium_mg": 35, "caffeine_mg": 0, "acidity": 5},
        "ingredients": ["Water", "Mango pulp", "Sugar", "Acidity regulator", "Antioxidant", "Preservatives"],
        "risk_tags": ["high_sugar", "mango", "preservative"],
        "good_for": ["Users without mango allergy taking it in controlled quantity"],
        "avoid_for": ["Users with diabetes", "Users with fatty liver", "Users with mango allergy"],
    },
    "Limca": {
        "display_name": "Limca",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 115, "sugar_g": 28, "sodium_mg": 52, "caffeine_mg": 0, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Lemon-lime flavour", "Citric acid", "Stabilizers", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "citrus", "preservative"],
        "good_for": ["Users with no metabolic or gastric concerns consuming occasionally"],
        "avoid_for": ["Users with high BP", "Users with acidity", "Users with diabetes"],
    },
    "MD.Diet": {
        "display_name": "Mountain Dew Diet",
        "category": "diet_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 5, "sugar_g": 0, "sodium_mg": 45, "caffeine_mg": 30, "acidity": 8},
        "ingredients": ["Carbonated water", "Artificial sweeteners", "Citrus flavour", "Citric acid", "Caffeine", "Preservatives"],
        "risk_tags": ["carbonated", "caffeinated", "artificial_sweetener", "citrus", "preservative"],
        "good_for": ["Adults reducing sugar compared with regular soda, only occasionally"],
        "avoid_for": ["Users with caffeine sensitivity", "Users with acidity", "Users sensitive to artificial sweeteners"],
    },
    "MD.Orig": {
        "display_name": "Mountain Dew",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 125, "sugar_g": 31, "sodium_mg": 55, "caffeine_mg": 31, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Citrus flavour", "Citric acid", "Caffeine", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "citrus", "preservative"],
        "good_for": ["Healthy adults taking it rarely and in small servings"],
        "avoid_for": ["Users with diabetes", "Users with high BP", "Users with acidity or GERD"],
    },
    "Maaza": {
        "display_name": "Maaza",
        "category": "fruit_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 135, "sugar_g": 32, "sodium_mg": 25, "caffeine_mg": 0, "acidity": 5},
        "ingredients": ["Water", "Mango pulp", "Sugar", "Acidity regulator", "Antioxidants", "Preservatives"],
        "risk_tags": ["high_sugar", "mango", "preservative"],
        "good_for": ["Users without sugar restrictions taking it occasionally"],
        "avoid_for": ["Users with diabetes", "Users with fatty liver", "Users with mango allergy"],
    },
    "P.Cherry": {
        "display_name": "Pepsi Cherry",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 118, "sugar_g": 28, "sodium_mg": 22, "caffeine_mg": 26, "acidity": 9},
        "ingredients": ["Carbonated water", "Sugar", "Cherry flavour", "Caramel colour", "Phosphoric acid", "Caffeine"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "preservative"],
        "good_for": ["Adults with no metabolic risks having rare servings"],
        "avoid_for": ["Users with diabetes", "Users with caffeine sensitivity", "Users with acidity"],
    },
    "P.Orig": {
        "display_name": "Pepsi",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 112, "sugar_g": 27, "sodium_mg": 24, "caffeine_mg": 25, "acidity": 9},
        "ingredients": ["Carbonated water", "Sugar", "Caramel colour", "Phosphoric acid", "Natural flavour", "Caffeine"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "preservative"],
        "good_for": ["Users without sugar, heart, or gastric concerns taking it occasionally"],
        "avoid_for": ["Users with diabetes", "Users with high BP", "Users with acidity or GERD"],
    },
    "P.Rsugar": {
        "display_name": "Pepsi Real Sugar",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 122, "sugar_g": 30, "sodium_mg": 25, "caffeine_mg": 25, "acidity": 9},
        "ingredients": ["Carbonated water", "Sugar", "Caramel colour", "Phosphoric acid", "Natural flavour", "Caffeine"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "preservative"],
        "good_for": ["Healthy adults taking very small occasional servings"],
        "avoid_for": ["Users with diabetes", "Users with obesity", "Users with GERD"],
    },
    "P.Zero": {
        "display_name": "Pepsi Zero Sugar",
        "category": "diet_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 3, "sugar_g": 0, "sodium_mg": 35, "caffeine_mg": 32, "acidity": 9},
        "ingredients": ["Carbonated water", "Artificial sweeteners", "Caramel colour", "Phosphoric acid", "Natural flavour", "Caffeine"],
        "risk_tags": ["carbonated", "caffeinated", "artificial_sweetener", "preservative"],
        "good_for": ["Users reducing sugar versus regular cola, only occasionally"],
        "avoid_for": ["Users with caffeine sensitivity", "Users with acidity", "Users avoiding artificial sweeteners"],
    },
    "P.diet": {
        "display_name": "Diet Pepsi",
        "category": "diet_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 3, "sugar_g": 0, "sodium_mg": 36, "caffeine_mg": 28, "acidity": 9},
        "ingredients": ["Carbonated water", "Artificial sweeteners", "Caramel colour", "Phosphoric acid", "Natural flavour", "Caffeine"],
        "risk_tags": ["carbonated", "caffeinated", "artificial_sweetener", "preservative"],
        "good_for": ["Adults needing lower sugar than standard cola, only rarely"],
        "avoid_for": ["Users with acidity", "Users with caffeine sensitivity", "Users sensitive to artificial sweeteners"],
    },
    "Pulpy_Orange": {
        "display_name": "Minute Maid Pulpy Orange",
        "category": "fruit_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 120, "sugar_g": 27, "sodium_mg": 18, "caffeine_mg": 0, "acidity": 6},
        "ingredients": ["Water", "Orange juice concentrate", "Orange pulp", "Sugar", "Acidity regulator", "Preservatives"],
        "risk_tags": ["high_sugar", "citrus", "preservative"],
        "good_for": ["Users without citrus sensitivity when consumed in moderation"],
        "avoid_for": ["Users with diabetes", "Users with citrus allergy", "Users with gastritis"],
    },
    "Slice": {
        "display_name": "Slice",
        "category": "fruit_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 138, "sugar_g": 33, "sodium_mg": 26, "caffeine_mg": 0, "acidity": 5},
        "ingredients": ["Water", "Mango pulp", "Sugar", "Acidity regulator", "Antioxidants", "Preservatives"],
        "risk_tags": ["high_sugar", "mango", "preservative"],
        "good_for": ["Users without sugar restrictions taking occasional small servings"],
        "avoid_for": ["Users with mango allergy", "Users with diabetes", "Users with fatty liver"],
    },
    "Sprite": {
        "display_name": "Sprite",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 110, "sugar_g": 27, "sodium_mg": 45, "caffeine_mg": 0, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Lemon-lime flavour", "Citric acid", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "citrus", "preservative"],
        "good_for": ["Healthy adults taking it occasionally"],
        "avoid_for": ["Users with diabetes", "Users with acidity", "Users with citrus allergy"],
    },
    "Thums_Up": {
        "display_name": "Thums Up",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 118, "sugar_g": 29, "sodium_mg": 21, "caffeine_mg": 28, "acidity": 9},
        "ingredients": ["Carbonated water", "Sugar", "Caramel colour", "Phosphoric acid", "Natural flavour", "Caffeine"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "preservative"],
        "good_for": ["Adults with no cardio-metabolic or gastric issues taking it rarely"],
        "avoid_for": ["Users with diabetes", "Users with high BP", "Users with acidity"],
    },
    "campa": {
        "display_name": "Campa Cola",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 116, "sugar_g": 28, "sodium_mg": 22, "caffeine_mg": 20, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Caramel colour", "Food acids", "Natural flavour", "Caffeine"],
        "risk_tags": ["high_sugar", "carbonated", "caffeinated", "preservative"],
        "good_for": ["Users without sugar or acidity issues in rare servings"],
        "avoid_for": ["Users with diabetes", "Users with GERD", "Users with caffeine sensitivity"],
    },
    "fizz": {
        "display_name": "Appy Fizz",
        "category": "sparkling_fruit_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 122, "sugar_g": 29, "sodium_mg": 20, "caffeine_mg": 0, "acidity": 7},
        "ingredients": ["Carbonated water", "Apple juice concentrate", "Sugar", "Acidity regulator", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "preservative"],
        "good_for": ["Users without diabetes or acidity issues, only occasionally"],
        "avoid_for": ["Users with diabetes", "Users with acidity", "Users controlling calories"],
    },
    "mirinda": {
        "display_name": "Mirinda Orange",
        "category": "carbonated_soft_drink",
        "serving_ml": 250,
        "nutrients": {"calories": 121, "sugar_g": 30, "sodium_mg": 27, "caffeine_mg": 0, "acidity": 8},
        "ingredients": ["Carbonated water", "Sugar", "Orange flavour", "Citric acid", "Food colours", "Preservatives"],
        "risk_tags": ["high_sugar", "carbonated", "citrus", "preservative"],
        "good_for": ["Users with no sugar or gastric concerns taking it rarely"],
        "avoid_for": ["Users with diabetes", "Users with citrus allergy", "Users with gastritis"],
    },
}

DEFAULT_DAILY_LIMITS = {
    "sugar_g": 25,
    "caffeine_mg": 200,
    "sodium_mg": 400,
    "soft_drink_servings": 1,
}


def beverage_choices() -> list[tuple[str, str]]:
    return [(key, value["display_name"]) for key, value in sorted(BEVERAGE_LIBRARY.items(), key=lambda item: item[1]["display_name"])]
